# Generated by Django 5.1.6 on 2025-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_idx_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Rating from 0.0 to 5.0', max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'address')},
        ),
    ]
