# Generated by Django 5.1.6 on 2025-03-31 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_alter_restaurant_latitude_alter_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, verbose_name='Price')),
                ('preparation_time', models.IntegerField(help_text='Preparation time in minutes', verbose_name='Preparation Time')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Image')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'MENU_ITEMS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='idx_menu_item_name'), models.Index(fields=['category'], name='idx_menu_item_category'), models.Index(fields=['restaurant'], name='idx_menu_item_restaurant'), models.Index(fields=['is_available'], name='idx_menu_item_availability')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'), models.CheckConstraint(condition=models.Q(('preparation_time__gte', 0)), name='preparation_time_positive')],
                'unique_together': {('name', 'restaurant')},
            },
        ),
    ]
